site_name: rag4gov
repo_url: https://github.com/laleye/rag4gov
site_url: https://laleye.github.io/rag4gov
site_description: RAG For Government
site_author: Fréjus Laleye
edit_uri: edit/main/docs/
repo_name: laleye/rag4gov
copyright: Maintained by <a href="https://laleye.com">laleye</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src/rag4gov"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/laleye/rag4gov
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/rag4gov

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
